Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    BramFactor: 1000000000
    ChannelsLastConversion: full
    Precision:
      default: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
    TransposeOutputs: false
IOType: io_parallel
InputData: null
InputShape: !!python/tuple
- 2
OutputDir: ./hls_output/hls4mlprj_pytorch_api_linear_Vitis_io_parallel
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
PytorchModel: !!python/object:__main__.SimpleModel
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules:
    fc: !!python/object:torch.nn.modules.linear.Linear
      _backward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _buffers: {}
      _forward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
      - []
      _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
      - []
      _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
      - []
      _is_full_backward_hook: null
      _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _modules: {}
      _non_persistent_buffers_set: !!set {}
      _parameters:
        bias: !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYCgAAADQ5MjEyMDM4MjRxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAA0OTIxMjAz
              ODI0cQFhLgEAAAAAAAAArTgDvw==
          - 0
          - !!python/tuple
            - 1
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
        weight: !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYCgAAADQ5MjEyMjk3OTJxAlgDAAAAY3B1cQNLAk50cQRRLoACXXEAWAoAAAA0OTIxMjI5
              NzkycQFhLgIAAAAAAAAA8XOtPjZ+1D0=
          - 0
          - !!python/tuple
            - 1
            - 2
          - !!python/tuple
            - 2
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
      _state_dict_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      in_features: 2
      out_features: 1
      training: false
  _non_persistent_buffers_set: !!set {}
  _parameters: {}
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: false
Stamp: 735fd24e
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
